### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="1.xlsx"
Content-Type: application/octet-stream

< C:/Users/Administrator/Desktop/1.xlsx


### 预览文件
GET {{media_host}}/media/open/preview/01191860ba4cc8e8c5b8d29032d064f4