### 授权码模式
### 第一步申请授权码(浏览器请求localhost:63070/auth/oauth/authorize?client_id=WebApp&response_type=code&scope=all&redirect_uri=http://www.kaizhi.edu.cn)
GET {{auth_host}}/auth/oauth/authorize?client_id=WebApp&response_type=code&scope=all&redirect_uri=http://www.kaizhi.edu.cn
### 第二步申请令牌，code需要修改
POST {{auth_host}}/auth/oauth/token?client_id=WebApp&client_secret=WebApp&grant_type=authorization_code&code=w1k1WE&redirect_uri=http://www.kaizhi.edu.cn

### 密码模式
#POST {{auth_host}}/auth/oauth/token?client_id=WebApp&client_secret=WebApp&grant_type=password&username=zhangsan&password=123
POST {{auth_host}}/auth/oauth/token?client_id=WebApp&client_secret=WebApp&grant_type=password&username=t1&password=111111

###校验jwt令牌，token需要修改
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2FpemhpLWVkdWNhdGlvbiJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTczMTc3MjM2OSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI2YTNmZmNiZC1lY2Q2LTQ0Y2UtOTZlZC04MmE3MWU1NWZmYzkiLCJjbGllbnRfaWQiOiJXZWJBcHAifQ.d4ffQdi66S-hcIGWEjMlL7xfzSIJdZ5Rw8qacNankk0